<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!-- 윗부분(header)을 따로 만들어 include -->
<%@include file="../header.jsp"%>

<!-- Logo -->
<h1 id="logo">
	<a href="/SpringProject/">교과과정</a>
</h1>
<p>3학년</p>
</div>
</section>
<!-- Features -->
<section id="features">
	<div class="container">
		<div class="table-wrapper">
			<table>
				<thead>
					<tr>
						<th>이수구분</th>
						<th>교과구분</th>
						<th>교과목명</th>
						<th>1학기</th>
						<th>2학기</th>
						<th>여름계절학기</th>
						<th>겨울계절학기</th>
					</tr>
				</thead>
				<tbody>
						<tr>
							<td>교양교과</td>
							<td>과업수행</td>
							<td>글쓰기와토론</td>
							<td>0</td>
							<td>2</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>교양교과</td>
							<td>직업의식</td>
							<td>참인성과진로</td>
							<td>1</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>무선네트워크</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>무선네트워크</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>클라우드컴퓨팅</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>빅데이터</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>서버프로그래밍</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>TCP/IP</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>모바일프로그래밍</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>인공지능</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>자율현장실습(하계)</td>
							<td>0</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>표준현장실습(하계)</td>
							<td>0</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>Front-End개발실습</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>SW프로젝트운영실습(씰습학기)</td>
							<td>0</td>
							<td>5</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>SW프로젝트운영실습(씰습학기)</td>
							<td>0</td>
							<td>5</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>SW프로젝트운영실습(씰습학기)</td>
							<td>0</td>
							<td>5</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>SW프로젝트운영실습(씰습학기)</td>
							<td>0</td>
							<td>5</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>Start-Up 프로젝트</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>소프트웨어공학</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>

<!-- 아랫부분(footer)을 따로 만들어 include -->
<%@include file="../footer.jsp"%>