<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!-- 윗부분(header)을 따로 만들어 include -->
<%@include file="../header.jsp"%>

<!-- Logo -->
<h1 id="logo">
	<a href="/SpringProject/">교과과정</a>
</h1>
<p>2학년</p>
</div>
</section>
<!-- Features -->
<section id="features">
	<div class="container">
		<div class="table-wrapper">
			<table>
				<thead>
					<tr>
						<th>이수구분</th>
						<th>교과구분</th>
						<th>교과목명</th>
						<th>1학기</th>
						<th>2학기</th>
						<th>여름계절학기</th>
						<th>겨울계절학기</th>
					</tr>
				</thead>
				<tbody>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>JAVA프로그래밍</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>Oracle SQL&PL/SQL</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>데이터베이스</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>엔터프라이즈서버관리</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>자료구조</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>NCS</td>
							<td>객체지향프로그래밍</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>표준현장실습(동계)</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
							<td>3</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>자율현장실습(동계)</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
							<td>3</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>S/W프로젝트</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>S/W프로젝트</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>JSP</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>사물인터넷</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공실습(선택)</td>
							<td>일반</td>
							<td>C#프로그래밍</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공이론(선택)</td>
							<td>NCS</td>
							<td>시스템분석설계</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공이론(선택)</td>
							<td>NCS</td>
							<td>운영체제</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
						<tr>
							<td>전공이론(선택)</td>
							<td>NCS</td>
							<td>정보보안</td>
							<td>0</td>
							<td>3</td>
							<td>0</td>
							<td>0</td>
						</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>

<!-- 아랫부분(footer)을 따로 만들어 include -->
<%@include file="../footer.jsp"%>